# Generated by Django 5.0.2 on 2024-02-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('needs_to_be_done', 'Needs to be done')], default='important', max_length=25)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('postponed', 'Postponed')], default='pending', max_length=25)),
            ],
        ),
    ]
